### ISSUE TITLE
编译时提示 “ CNctxConfigParam” was not declared

### ISSUE THREAD

**Issue by eiffelmen** [Cambricon/mlu-ops#1]
下载仓库后，执行build.sh文件编译，提示 CNct 开头的一些类未声明的错误。
`test/mlu_op_gtest/src/executor.cpp:1411:3: error: ‘CNctxConfigParam’ was not declared in this scope
   CNctxConfigParam ctx_conf_param, check_param;`
`core/context.cpp:105:3: error: ‘CNctxConfigParam’ was not declared in this scope
   CNctxConfigParam ctx_conf_param;`

另外 希望作者在README 标注项目所需依赖：libgtest-dev libxml2-dev libprotobuf-dev protobuf-compiler

**Comment by lihui-ngpf** [comment]
看报错的话，应该是cn_api.h没有被引用到，请检查下$NEUWARE_HOME/include文件夹下是否有cn_api.h。
CNctxConfigParam类型是在cn_api.h中被定义的。

**Comment by hiok2000** [comment]
Firstly, cn_api.h has no CNctxConfigParam
Secondly, I have checked $NEUWARE_HOME/include and it has cn_api.h

**Comment by mingfengwuye** [comment]
> 

请确认下CNToolkit版本是否匹配。该repo依赖 CNToolkit v2.3.2 或更高版本

**Comment by wushaoqiang2168** [comment]
问题是否得到解决？
