### ISSUE TITLE
active算子与非active算子的使用差别及选择

### ISSUE THREAD

**Issue by Terrencezwy** [Cambricon/mlu-ops#1020]
如指数或平方根运算，在bang接口中存在__bang_active_pow2()及__bang_pow2()，sqrt同理，这种情况下应如何选择，内部实现上是否有精度或性能的区别？

**Comment by duzekunKTH** [comment]
相关一手信息可以翻阅在线文档 [Cambricon BANG C Developer Guide](https://www.cambricon.com/docs/sdk_1.15.0/cntoolkit_3.7.2/cambricon_bang_c_4.7.2/index.html) ，在在线文档中可以搜索相关算子名。
`__bang_pow2()` 是指数计算运算。
`__bang_active_pow2()` 的算子行为是通过查表完成指数运算。该算子的输入有较大的限制：只能传整数，且限制大小范围。
