### ISSUE TITLE
[Feature] (bangc-ops):Faster R-CNN trans OBB - poly_nms: modify poly_nms interface restrictions

### ISSUE THREAD

**Issue by guzhonghao** [Cambricon/mlu-ops#131]
1. 接口限制由输入boxes的顶点坐标必须全是顺时针或者全是逆时针改为  输入boxes的每个box可以是顺时针或者逆时针；
2. 计算IOU的方法改为inline，性能提升30%左右

**Comment by guzhonghao** [comment]
mluops PR：https://github.com/Cambricon/mlu-ops/pull/129

**Comment by guzhonghao** [comment]
generator PR：https://github.com/Cambricon/mlu-ops-generator/pull/20

**Comment by WangYuan-cn** [comment]
done
