### ISSUE TITLE
[New Op] generate_proposals_v2

### ISSUE THREAD

**Issue by WangYuan-cn** [Cambricon/mlu-ops#137]
- name：generate_proposals_v2
- related-network：Fmaskrcnn
- reference：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/generate_proposals_v2_op.cc#L292

**Comment by guzhonghao** [comment]
设计方案PR: https://github.com/Cambricon/mlu-ops/pull/155/files

**Comment by guzhonghao** [comment]
code PR：https://github.com/Cambricon/mlu-ops/pull/191

**Comment by guzhonghao** [comment]
generator PR:https://github.com/Cambricon/mlu-ops-generator/pull/28
