### ISSUE TITLE
Add data type and error codes in .h file

### ISSUE THREAD

**Issue by GraceGuanH** [Cambricon/mlu-ops#148]
Please describe the missing data types and error codes in .h file.

**Missing data types:**
mlu‑OpTensorDescriptor_t
mluOpHandle_t

**Missing error codes:**
MLUOP_STATUS_SUCCESS
MLUOP_STATUS_BAD_PARAM
MLUOP_STATUS_NOT_SUPPORTED

**Comment by WangYuan-cn** [comment]
https://github.com/Cambricon/mlu-ops/pull/167
