### ISSUE TITLE
[bug report] Bangpy tcp script assign结果错误

### ISSUE THREAD

**Issue by Alaskra** [Cambricon/mlu-ops#153]
环境：bangpy2.0.3
在使用tcp script重构算子过程中发现，
使用语句`tcp.assign(ex1, 15)`，如果ex1是float16类型的nram buffer的话，赋值结果会错误（tcp.print(ex1[0]的打印结果是0或者接近0的数字），15换成其他数（比如15.0，1，1.0）也是同样错误。换成语句`tcp.assign(ex1, tcp.cast(15, self.dtype))`结果就正确了。

**Comment by zhangyicole** [comment]
经过测试，该接口确实存在bug，已列入下一版本修复列表。现在使用，麻烦按`tcp.assign(src, tcp.cast(value, dtype))`这种形式进行使用。

**Comment by zhangyicole** [comment]
该问题已在2.1.0版本解决
