### ISSUE TITLE
bangpy2.1报错error: Unknown identifier v_2.

### ISSUE THREAD

**Issue by Alaskra** [Cambricon/mlu-ops#162]
使用bangpy2.1重构算子的时候遇到下面问题：
![image](https://user-images.githubusercontent.com/49367127/187370178-6884436b-82df-46c7-af37-f10692115dc5.png)
判断arch的接下来第一条语句会报错，如果注释掉判断，就不报错。
而且测试时如果使用float32不会报错，使用float16会报错。
还发现只要有那种编译时可以判断的if语句，就会报这种错误。
这是代码：
[Archive.tar.gz](https://github.com/Cambricon/mlu-ops/files/9450430/Archive.tar.gz)

**Comment by zhangyicole** [comment]
多重控制流嵌套暂不支持推导，可否将两部分控制流的展开合并下，虽然代码有些冗余。后续版本会修复这个问题。

**Comment by Alaskra** [comment]
好的，那就先删除针对mlu3xx的优化分支语句了（应该对性能影响不大），等更新修复再改回来

**Comment by SYangDong** [comment]
已修复
