### ISSUE TITLE
mlu2xx上正常的测例在mlu370上报failed to invoke

### ISSUE THREAD

**Issue by cnzjyjp** [Cambricon/mlu-ops#170]
代码和测试文件如下：
[cross.zip](https://github.com/Cambricon/mlu-ops/files/9459642/cross.zip)
测试文件中打开的那条测例在mlu2系列上通过，在mlu370-s4上面测试多次均报以下错误：
![Snipaste_2022-08-31_15-49-35](https://user-images.githubusercontent.com/37297476/187622838-f275edc7-2282-4177-bbe4-53b827a8baa6.png)
请问是为什么呢，是否是因为超出了mlu370的数据上限？

**Comment by zhangyicole** [comment]
请问经过测试，还存在问题吗？是否是代码里越界？

**Comment by cnzjyjp** [comment]
@zhangyicole 因为370上面是m8的卡，所以使用eager module会报错，暂时还没有调试；
但是在mlu2系列上都是通过的，感觉也不是哪里越界

**Comment by cnzjyjp** [comment]
@zhangyicole 想问一下370的nram大小是多少？可能buffer分配超了
