### ISSUE TITLE
bangpy2.1.1 变量赋值负数解析有误

### ISSUE THREAD

**Issue by SS7D631** [Cambricon/mlu-ops#183]
例： test = -7.5
编译报错：error: Unsupported Op

![image](https://user-images.githubusercontent.com/46569727/188824203-08ee44d0-13c4-4471-8c80-c4ec5197359a.png)

**Comment by zhangyicole** [comment]
确认bug，下个版本会修复

**Comment by SYangDong** [comment]
已修复
