### ISSUE TITLE
[Bug]/[CoreDump] : A sample of code bug issue submission

### ISSUE THREAD

**Issue by zhangyicole** [Cambricon/mlu-ops#19]
**问题描述：**
简述出现的问题。

**期望的代码行为：**
预期的代码行为，或输出结果，最好能附加代码片段。

**实际运行的代码行为：**
实际运行产生的错误或core dump的结果，最好附加相关的错误截图。

**运行环境**:
代码分支：请将出错的代码push到一个分支上，并附加分支链接。
BUG复现步骤：请描述如何复现出错的问题，包括如何执行命令等。
Bangpy版本：使用命令pip show  bangpy查看，最好附上命令行运行截图。
Cntoolkit工具链版本：cncc --version，最好附上命令行运行截图。

**Comment by WangYuan-cn** [comment]
@zhangyicole 这个issue是否解决？
