### ISSUE TITLE
bangpy: time_evaluator可以忽略个别不正常的数据吗？

### ISSUE THREAD

**Issue by Alaskra** [Cambricon/mlu-ops#20]
## 问题描述
使用timeevaluator测时间时，如果repeat设置的比较大，会出现这种特别大的不正常的时间。在实测过程中发现，这种不正常时间会对取平均的结果造成较大的波动。算子代码中只包含纯IO，所以应该和计算逻辑没关系。请问time_evaluator这个接口可以支持去除不正常数据吗？

## 相关截图
![2022-04-27_11-52](https://user-images.githubusercontent.com/49367127/165437977-46f52ae9-33ca-4b52-ae58-dce2a57cdce1.png)

## 运行环境
![image](https://user-images.githubusercontent.com/49367127/165438105-d3344a14-64aa-4f74-9fa7-a1cc95ef40d1.png)

**Comment by Alaskra** [comment]
发现使用中位数`t.median`来衡量可以解决这个问题，也许比去平均更合适一点

**Comment by zhangyicole** [comment]
如果repeat设置的比较大，会出现这种特别大的不正常的时间。这种情况出现的概率很大吗？稳定出现吗？硬件的波动确实有可能造成多次repeat运行时个别时间不准确，但这种情况应该不会常见的。

**Comment by Alaskra** [comment]
repeat设置成100的话几乎每次都有，如果是10的话就没了

**Comment by SYangDong** [comment]
可以看看这个mr：https://github.com/apache/tvm/pull/11465， repeat比较大确实存在这个问题

**Comment by SYangDong** [comment]
可以看看这个mr：https://github.com/apache/tvm/pull/11465， repeat比较大确实存在这个问题

**Comment by Alaskra** [comment]
嗯好的，问题不大，我先关闭issue了
