### ISSUE TITLE
关于从SRAM拷数据到GDRAM的问题

### ISSUE THREAD

**Issue by pingmu123** [Cambricon/mlu-ops#23]
**问题描述：**\
数据从SRAM拷到GDRAM时，打印查看后发现并没有拷进去。

**期望的代码行为：**
```
with self.tcp.block("data_copy"):
    self.tcp.memcpy(buffer_out_s[begin:end], buffer_io_n)
    with self.tcp.if_scope(j==2):
        st.assign(start-2*data_each_time)
        # with self.tcp.if_scope(tcp.all(task_id==0,i==2)):
        #     self.tcp.print(buffer_out_s[begin:begin+data_each_time])
              self.tcp.memcpy(buffer_out[st:stop],buffer_out_s[begin-2*data_each_time:end])
              self.tcp.sync_cluster()
        # with self.tcp.if_scope(tcp.all(task_id==0,i==2)):
        #     self.tcp.print(buffer_out[st:st+data_each_time])
```
期望buffer_out的值与buffer_out_s里面的值一致。

**实际运行的代码行为：**\
buffer_out初始值为全0：`data_out_dev = bangpy.Array(np.zeros(data_out.shape, dtype.as_numpy_dtype), dev)`\
拷贝后输出的仍然是全0，也即数据没有拷入进去

**运行环境：**\
代码分支：[分支链接](https://github.com/pingmu123/mlu-ops.git)\
bug复现步骤：定位到bangpy-ops/ops/hard_sigmoid/hard_sigmoid.py文件184-193行，修改相关print语句，然后直接python3 mytest.py即可\
bangpy版本：1.3.1\
cncc：v3.6.1
![bangpy和cncc版本](https://user-images.githubusercontent.com/102028822/165430656-ac6217b7-1078-41dc-be44-7420261b7411.png)

大致情况如上述，不知道是哪里理解错了，感谢！

**Comment by pingmu123** [comment]
找到问题了，应该是`self.tcp.launch_cluster(TaskType.BLOCK)`导致索引地址出错了，然后现在把它改成`self.tcp.launch_cluster(TaskType.UNIONxx)`了。

**Comment by zhangyicole** [comment]
这个是代码本身的逻辑问题吗？已解决的话是否可以关闭？

**Comment by pingmu123** [comment]
> 这个是代码本身的逻辑问题吗？已解决的话是否可以关闭？

您好，是代码本身的逻辑问题，是我弄错了，可以关闭，谢谢！
