### ISSUE TITLE
poly_nms算子可以集成在MLU100 V8.2.1SDK Caffe环境中吗

### ISSUE THREAD

**Issue by SunshineJZJ** [Cambricon/mlu-ops#238]
请问poly_nms算子可以集成在MLU100 V8.2.1SDK Caffe环境中吗，
目前在MLU100 caffe环境中尝试移植旋转框目标检测算法（ROITransformer），输出层涉及到旋转框的IOU计算。
https://github.com/Cambricon/mlu-ops/tree/master/bangc-ops/kernels/poly_nms

**Comment by guzhonghao** [comment]
请问问题解决了吗？ 如果有问题，可以再细化问题继续在github留言，我们会及时回复。

**Comment by SunshineJZJ** [comment]
> 请问问题解决了吗？ 如果有问题，可以详细描述下遇到的问题，在github留言，我们会及时回复。

感谢回复，我把调试的代码和说明放在压缩文件里了，麻烦您调试一下看看。
[ploy_nms.zip](https://github.com/Cambricon/mlu-ops/files/9906374/ploy_nms.zip)

**Comment by guzhonghao** [comment]
你好，查看代码， 计算
 Bbox_B[0]=0.5; Bbox_B[1]=0.5; Bbox_B[2]=1.5; Bbox_B[3]=0.5; 
  Bbox_B[4]=1.5; Bbox_B[5]=1.5; Bbox_B[6]=0.5; Bbox_B[7]=1.5; 
 和
 half Bbox_A[8] = { 0.3,0.2, 0.3,1.4, 0.6,0.6, 1.3,0.2};  // 凹
两个box的相交面积为0.032，计算结果正确。

 Bbox_B[0]=0.5; Bbox_B[1]=0.5; Bbox_B[2]=1.5; Bbox_B[3]=0.5; 
  Bbox_B[4]=1.5; Bbox_B[5]=1.5; Bbox_B[6]=0.5; Bbox_B[7]=1.5; 
 和half Bbox_A[8] = { 0, 0, 1, 0, 1, 1, 0, 1};              // 凸
两个box的相交面积为0.25，计算结果正确。

**Comment by SunshineJZJ** [comment]
> Bbox_B[0]=0.5; Bbox_B[1]=0.5; Bbox_B[2]=1.5; Bbox_B[3]=0.5;
> Bbox_B[4]=1.5; Bbox_B[5]=1.5; Bbox_B[6]=0.5; Bbox_B[7]=1.5;
> 和half Bbox_A[8] = { 0, 0, 1, 0, 1, 1, 0, 1}; // 凸

感谢回复；
我又调试了一下，现在可以正确计算了，但是我调试时发现一个框是顺时针，另一个框是逆时针才可以正确计算。
Bbox_B[0]=0.5; Bbox_B[1]=0.5; Bbox_B[2]=1.5; Bbox_B[3]=0.5;
Bbox_B[4]=1.5; Bbox_B[5]=1.5; Bbox_B[6]=0.5; Bbox_B[7]=1.5;
和half Bbox_A[8] = { 0, 0, 0, 1, 1, 1, 1, 0}; // 凸
如上设置，才可以正确计算。
api里说的是两框需要同时是顺时针或者逆时针，请问这是为什么呢？

**Comment by guzhonghao** [comment]
抱歉, 理解可能有歧义, 算法需要保证输入的box坐标不是乱序排序即可,  不需要保证所有的输入都是顺时针排序或者都是逆时针排序.

比如 输入 box1,box2, 只需要保证输入的box1不是乱序排序, box2坐标不是乱序排序,  无论box1和box2是顺时针还是逆时针顺序,都可以得到正确计算结果.

**Comment by SunshineJZJ** [comment]
> 

好的 非常感谢！

**Comment by SunshineJZJ** [comment]
您好 上述算子实际应用在倾斜框IOU计算时还是不正确，我把代码、倾斜框测试样例以及说明文档放在压缩文件中了，麻烦您看下。[poly_nms.zip](https://forum.cambricon.com/uploadfile/user/file/20221223/1671790275268615.zip)

**Comment by WangYuan-cn** [comment]
收到，感谢您的反馈。我们会对上述问题进行分析，待分析结束后给您反馈

**Comment by SunshineJZJ** [comment]
> 

您好 有结果了吗

**Comment by mahxn0** [comment]
> > 
> 
> 您好 有结果了吗
您好，看了您的代码，MLU是按照float16计算的，而cpu是float32
float16的有效位数是4~5位，因此输入和输出在计算过程是会存在误差的，看了样例一的结果，属于正常的误差范围．
样例1: 
我这边跑出来的结果：
```
------polyArea------>:0.016022 
area route1:0.016022 
intersect:0.016022 
------polyArea------>:0.017136 
------polyArea------>:0.016708 
-------------------IOU------->:0.898926
```
样例2:交集面积也是0 和cpu一致
```
area route1:0.000000 
intersect:0.000000 
------polyArea------>:0.017136 
------polyArea------>:0.015793 
-------------------IOU------->:0.000000
```
[ploy_nms_kernel.zip](https://github.com/Cambricon/mlu-ops/files/10683953/ploy_nms_kernel.zip)

**Comment by duzekunKTH** [comment]
@SunshineJZJ 您好，请问上述回复是否解答了您的疑问？
