### ISSUE TITLE
构造函数中无法执行tcp.target()函数

### ISSUE THREAD

**Issue by testouya** [Cambricon/mlu-ops#244]
@eg.module
class PairwiseDistance(object):
       
    """Operator description:
    Add the data in the two buffers.
    """
    def __init__(self, buffer_size: ty.int32, dtype: ty.string) -> None:
        self.dtype = dtype
        self.single_buffer_size = buffer_size
        self.bp = tcp.target()   #这句话会有问题
        #tcp.print("ce shi")

这样写会报错。
Exception: module 'bangpy.tcp' has no attribute 'target'

**Comment by wushaoqiang2168** [comment]
问题是否已解决？

**Comment by testouya** [comment]
没有，换个写法了。

**Comment by wushaoqiang2168** [comment]
好的，issue可以关闭了吗？

**Comment by testouya** [comment]
可以了。&nbsp;


阿吉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月18日(星期五) 晚上6:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Cambricon/mlu-ops] 构造函数中无法执行tcp.target()函数 (Issue #244)





 
好的，issue可以关闭了吗？

**Comment by duzekunKTH** [comment]
感谢您的提问！
根据仓库规划与维护规范，bangpy 将会在 x 版本升级时移除。
若后续有 bangpy 开发需求，请使用 mlu-ops v0.y.z 版本。
