### ISSUE TITLE
关于bangpy自动流水生成的代码逻辑问题

### ISSUE THREAD

**Issue by Alaskra** [Cambricon/mlu-ops#26]
![image](https://user-images.githubusercontent.com/49367127/165541833-296c322b-7107-4b8c-ba84-483bed979942.png)
上图下面红框是使用print(f.get_source())打印出的对应bangc代码，代码for循环部分的顺序是memcpy_async, memcpy_async,  __bang_add, memcpy_async。
但是按我的理解，流水要使计算和store+load同步的话，顺序应该是：memcpy_async, memcpy_async, memcpy_async, __bang_add才对。
bangc中的一元模板就是先写异步store+load语句，再写计算逻辑的：
![image](https://user-images.githubusercontent.com/49367127/165543659-2f52221a-3b86-439b-83ba-8cabfecf772f.png)

**Comment by zhangyicole** [comment]
在使用流水的时候，Load， Srtore，Compute和Load， Compute，Srtore这两种代码的排列顺序都是可以的，只要保证Load， Compute，Srtore三者排列后不存在数据依赖，流水可以正确运行即可。异步的memcpy和普通的计算语句在书写时候的顺序不会影响他们的并行执行。

**Comment by Alaskra** [comment]
好的谢谢
