### ISSUE TITLE
poly_nms算子初始化问题

### ISSUE THREAD

**Issue by SunshineJZJ** [Cambricon/mlu-ops#267]
https://github.com/Cambricon/mlu-ops/blob/ae3b78a6487e663ff93cb6d940048d7db863b0ed/bangc-ops/kernels/poly_nms/intersect_area.h#L33
在ploy_nms算子计算IOU面积时涉及一个变量：constexpr uint32_t BIT_FLOAT_NEG_1 = 0x80000000; 
我想在MLU100上运行一下这个算法，改动如下：
float => half,    uint32_t => uint16_t
当检测框是凹四边形时，计算结果是正确的；
检测框是凸多边形时，计算结果是错误的，原因是BIT_FLOAT_NEG_1初始化值不正确，
请问在MLU100设备上BIT_FLOAT_NEG_1值应该怎么样初始化？

**Comment by guzhonghao** [comment]
修改成half类型，BIT_FLOAT_NEG_1 值需要做如下修改：
 uint16_t BIT_FLOAT_NEG_1 = 0x8000;

**Comment by wushaoqiang2168** [comment]
问题是否得到解决？
