### ISSUE TITLE
多个core同时IO如何优化性能

### ISSUE THREAD

**Issue by Alaskra** [Cambricon/mlu-ops#27]
为了研究增加核数所带来的加速效果，我固定每个core处理2^24*3个float数据，以下是不同core数的运行时间（ms）：
![image](https://user-images.githubusercontent.com/49367127/165662400-26c7af4b-00a5-4b4f-b846-bc886542d632.png)
三列分别表示100个add，1个add和纯IO的运算。
可以看到，纯IO的情况，core数增加，单个core的性能下降了很多，而100add下降的很少。
我猜测是多个core的IO竞争gdram带宽，导致单个core性能下降。而对于计算密集型的100add运算，因为IO时间占比小，所以gdram带宽的竞争就比较小。
目前在mlu290上跑满64个core，IO的吞吐量最多约600GB/s，只能达到60%的效率。我想尽量跑满带宽，请问有什么优化的手段吗？

**Comment by stuart-yang** [comment]
这个问题和issue#24有些相似。引用在里边提到的方法：
1. 使用sram作为数据中转，利用sram和 gdram/nram之间的大的带宽（比较一个cluster中4个core共用的gdram到nram带宽）
2. 使用流水线，让计算和数据搬运并行起来，掩盖访问延时

**Comment by Alaskra** [comment]
![image](https://user-images.githubusercontent.com/49367127/166904028-e8293b40-d428-441f-9408-011f103f0a9d.png)
你好，我有测试过发现SRAM和GDRAM之间的IO并没有比NRAM好，甚至会略差。上图的第一项是数据再GDRAM和SRAM之间拷贝，第二项是GDRAM和NRAM之间拷贝。都使用了64个core，纯IO。在考虑各个core之间是否会存在带宽竞争导致吞吐量没有达到预期。

**Comment by zhangyicole** [comment]
这是正常的现象，无法跑满带宽是硬件的制约，你测得的数据已经接近实际使用场景下的带宽了。如果想要再进一步提升带宽，参考[[stuart-yang](https://github.com/stuart-yang)](https://github.com/Cambricon/mlu-ops/issues/27#issuecomment-1118319911)里提到的使用sram作为数据中转，并同时尝试使用多级流水，如input拷贝使用sram中转，output拷出直接使用nram到gdram的拷贝，在流水的情况下，两者拷贝并行，可以提升带宽。
