### ISSUE TITLE
mlu-ops仓中部分代码和文档中含有cnnl等字样，需要删除或者修改

### ISSUE THREAD

**Issue by wushaoqiang2168** [Cambricon/mlu-ops#272]
![{ae8fa5f0-62cd-4539-a437-c72aac60c314}](https://user-images.githubusercontent.com/107451865/198176795-e6699964-ed0e-42d3-abc2-f269f5f611bb.png)

**Comment by mahxn0** [comment]
https://github.com/Cambricon/mlu-ops/pull/282  已修改

**Comment by wushaoqiang2168** [comment]
[Docs](bangc-ops): Update prior_box designed docs. #282

**Comment by wushaoqiang2168** [comment]
[Docs](bangc-ops): Update prior_box designed docs. #282

**Comment by DanieeelLiu** [comment]
https://github.com/Cambricon/mlu-ops/pull/279已修改
