### ISSUE TITLE
变量数据长度超过1G的时候会出现TVMerror

### ISSUE THREAD

**Issue by Sunshine-KK** [Cambricon/mlu-ops#28]
给input参数传入的数据长度超过2**30的时候，会出现报错：
TVMError: Bind have an unmet assertion: (2147483648 == int32(arg0.shape[0])),  on argument arg0.shape[0]

请问这个是对输入数据的限制吗？

**Comment by stuart-yang** [comment]
麻烦给出可以重现问题的完整代码。 如果只是将buffer某个形状设置成2**30， 遇到下面error，不能重现问题。
MmeoryError: Unable to allocate 2.00 GiB for an array with shape (1073741824, 0) ...

**Comment by zhangyicole** [comment]
对输入数据是没有限制的，请给出完整的环境或者代码以便于我们复现，查找问题。

**Comment by Sunshine-KK** [comment]
代码如下，麻烦帮忙排查一下问题：
`from cmath import e
from bangpy import tcp
from bangpy.tcp.runtime import TaskType
from bangpy.platform.bang_config import TARGET
import bangpy as bp    
import numpy as np

target = "mlu290"
tcps = tcp.TCP(target)

#设置核信息
task_type = TaskType.UNION4
tcps.launch_cluster(task_type.value)
task_num = task_type.value * 4
tcps.launch_task(task_num, 1, 1) 

#设置数据类型和数据个数
dtype = bp.float32
dtype_sz = dtype.bytes
length = 2**31
shape = (length, )

#设置硬件相关信息
compute_row = 32
nram_size = TARGET(target).nram_size 
single_buffer_size = 64 * 128 // dtype.bytes * compute_row

task_id = tcps.taskId

#每次处理的数据量
data_calculated_each_time = single_buffer_size // dtype_sz
data_calculated_each_task  = length // task_num
with tcps.if_scope(task_id == task_num - 1):
    data_calculated_each_task = length // task_num + length % task_num

#每个task需要循环多少次
loop_num = tcps.Scalar(bp.int32, name="loop_num")
loop_num.assign(data_calculated_each_task // data_calculated_each_time)

# global的数据buffer
input = tcps.Buffer(shape=shape, name="input", dtype=dtype, scope="global")
target = tcps.Buffer(shape=shape, name="target", dtype=dtype, scope="global")
out = tcps.Buffer(shape=shape, name="output", dtype=dtype, scope="global")
reduction = tcps.SizeVar(name="reduction")


# 分块处理相关变量
start = tcps.Scalar(bp.int32, name="start")
start.assign(task_id * (length // task_num))
stop = tcps.Scalar(bp.int32, name="stop")

#对于每个task里面的每次buffer计算进行流水线处理
with tcps.for_range(begin = 0, end = loop_num, stage = 1) as i :
    buffer_input = tcps.Buffer(shape=(data_calculated_each_time,), name="input_N", dtype=dtype, scope="nram")
    buffer_target = tcps.Buffer(shape=(data_calculated_each_time,), name="target_N", dtype=dtype, scope="nram")
    buffer_out = tcps.Buffer(shape=(data_calculated_each_time,), name="OUTPUT_N", dtype=dtype, scope="nram")
        
    with tcps.block("data_copy") :
        tcps.memcpy(buffer_input[:data_calculated_each_time], input[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])
        tcps.memcpy(buffer_target[:data_calculated_each_time], target[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])

    with tcps.block("compute") :
        pass
    
    with tcps.block("data_copy") :
        with tcps.if_scope(reduction == 0) :
            tcps.memcpy(out[start + data_calculated_each_time * i:start + data_calculated_each_time * (i+1)], buffer_out[:data_calculated_each_time])

#处理每个task的尾部数据
with tcps.if_scope(data_calculated_each_task % data_calculated_each_time != 0):
    start.assign(start + data_calculated_each_time * loop_num)
    stop.assign(start + data_calculated_each_task % data_calculated_each_time)
    #data copy
    tcps.memcpy(buffer_input[:stop-start], input[start:stop])
    tcps.memcpy(buffer_target[:stop-start], target[start:stop]) 
    tcps.divide(buffer_input[:stop-start], buffer_target[:stop-start], buffer_input[:stop-start])
    tcps.log(buffer_input[:stop-start], buffer_input[:stop-start], high_precision = False)
    tcps.multiply(buffer_out[:stop-start], buffer_target[:stop-start], buffer_input[:stop-start])
    tcps.memcpy(out[start:stop], buffer_out[:stop-start])  

f = tcps.BuildBANG(inputs=[input, target, reduction], outputs=[out], kernel_name="kidivloss")


######################################################################################

data_input =  np.random.uniform(low=0, high=1, size=(length,))
data_target = np.random.uniform(low=0, high=1, size=(length,)).astype(dtype.as_numpy_dtype)

data_out = np.multiply(data_target, np.log(np.divide(data_target, data_input)))

dev = bp.device(0)

data_input_dev = bp.Array(data_input.astype(dtype.as_numpy_dtype), dev)
data_target_dev = bp.Array(data_target.astype(dtype.as_numpy_dtype), dev)
data_out_dev = bp.Array(np.zeros(data_out.shape, dtype.as_numpy_dtype), dev)

reduction = 0
f(data_input_dev, data_target_dev, reduction, data_out_dev)`

**Comment by Sunshine-KK** [comment]
`from cmath import e
from bangpy import tcp
from bangpy.tcp.runtime import TaskType
from bangpy.platform.bang_config import TARGET
import bangpy as bp    
import numpy as np

target = "mlu290"
tcps = tcp.TCP(target)

#设置核信息
task_type = TaskType.UNION4
tcps.launch_cluster(task_type.value)
task_num = task_type.value * 4
tcps.launch_task(task_num, 1, 1) 

#设置数据类型和数据个数
dtype = bp.float32
dtype_sz = dtype.bytes
length = 2**31
shape = (length, )

#设置硬件相关信息
compute_row = 32
nram_size = TARGET(target).nram_size 
single_buffer_size = 64 * 128 // dtype.bytes * compute_row

task_id = tcps.taskId

#每次处理的数据量
data_calculated_each_time = single_buffer_size // dtype_sz
data_calculated_each_task  = length // task_num
with tcps.if_scope(task_id == task_num - 1):
    data_calculated_each_task = length // task_num + length % task_num

#每个task需要循环多少次
loop_num = tcps.Scalar(bp.int32, name="loop_num")
loop_num.assign(data_calculated_each_task // data_calculated_each_time)

# global的数据buffer
input = tcps.Buffer(shape=shape, name="input", dtype=dtype, scope="global")
target = tcps.Buffer(shape=shape, name="target", dtype=dtype, scope="global")
out = tcps.Buffer(shape=shape, name="output", dtype=dtype, scope="global")
reduction = tcps.SizeVar(name="reduction")


# 分块处理相关变量
start = tcps.Scalar(bp.int32, name="start")
start.assign(task_id * (length // task_num))
stop = tcps.Scalar(bp.int32, name="stop")

#对于每个task里面的每次buffer计算进行流水线处理
with tcps.for_range(begin = 0, end = loop_num, stage = 1) as i :
    buffer_input = tcps.Buffer(shape=(data_calculated_each_time,), name="input_N", dtype=dtype, scope="nram")
    buffer_target = tcps.Buffer(shape=(data_calculated_each_time,), name="target_N", dtype=dtype, scope="nram")
    buffer_out = tcps.Buffer(shape=(data_calculated_each_time,), name="OUTPUT_N", dtype=dtype, scope="nram")
        
    with tcps.block("data_copy") :
        tcps.memcpy(buffer_input[:data_calculated_each_time], input[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])
        tcps.memcpy(buffer_target[:data_calculated_each_time], target[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])

    with tcps.block("compute") :
        pass
    
    with tcps.block("data_copy") :
        with tcps.if_scope(reduction == 0) :
            tcps.memcpy(out[start + data_calculated_each_time * i:start + data_calculated_each_time * (i+1)], buffer_out[:data_calculated_each_time])

#处理每个task的尾部数据
with tcps.if_scope(data_calculated_each_task % data_calculated_each_time != 0):
    start.assign(start + data_calculated_each_time * loop_num)
    stop.assign(start + data_calculated_each_task % data_calculated_each_time)
    #data copy
    tcps.memcpy(buffer_input[:stop-start], input[start:stop])
    tcps.memcpy(buffer_target[:stop-start], target[start:stop]) 
    tcps.divide(buffer_input[:stop-start], buffer_target[:stop-start], buffer_input[:stop-start])
    tcps.log(buffer_input[:stop-start], buffer_input[:stop-start], high_precision = False)
    tcps.multiply(buffer_out[:stop-start], buffer_target[:stop-start], buffer_input[:stop-start])
    tcps.memcpy(out[start:stop], buffer_out[:stop-start])  

f = tcps.BuildBANG(inputs=[input, target, reduction], outputs=[out], kernel_name="kidivloss")


######################################################################################

data_input =  np.random.uniform(low=0, high=1, size=(length,))
data_target = np.random.uniform(low=0, high=1, size=(length,)).astype(dtype.as_numpy_dtype)

data_out = np.multiply(data_target, np.log(np.divide(data_target, data_input)))

dev = bp.device(0)

data_input_dev = bp.Array(data_input.astype(dtype.as_numpy_dtype), dev)
data_target_dev = bp.Array(data_target.astype(dtype.as_numpy_dtype), dev)
data_out_dev = bp.Array(np.zeros(data_out.shape, dtype.as_numpy_dtype), dev)

reduction = 0
f(data_input_dev, data_target_dev, reduction, data_out_dev)`

**Comment by Sunshine-KK** [comment]
`from cmath import e
from bangpy import tcp
from bangpy.tcp.runtime import TaskType
from bangpy.platform.bang_config import TARGET
import bangpy as bp    
import numpy as np

target = "mlu290"
tcps = tcp.TCP(target)

task_type = TaskType.UNION4
tcps.launch_cluster(task_type.value)
task_num = task_type.value * 4
tcps.launch_task(task_num, 1, 1) 

dtype = bp.float32
dtype_sz = dtype.bytes
length = 2**31
shape = (length, )

compute_row = 32
nram_size = TARGET(target).nram_size 
single_buffer_size = 64 * 128 // dtype.bytes * compute_row

task_id = tcps.taskId

data_calculated_each_time = single_buffer_size // dtype_sz
data_calculated_each_task  = length // task_num
with tcps.if_scope(task_id == task_num - 1):
    data_calculated_each_task = length // task_num + length % task_num

loop_num = tcps.Scalar(bp.int32, name="loop_num")
loop_num.assign(data_calculated_each_task // data_calculated_each_time)

input = tcps.Buffer(shape=shape, name="input", dtype=dtype, scope="global")
target = tcps.Buffer(shape=shape, name="target", dtype=dtype, scope="global")
out = tcps.Buffer(shape=shape, name="output", dtype=dtype, scope="global")
reduction = tcps.SizeVar(name="reduction")

start = tcps.Scalar(bp.int32, name="start")
start.assign(task_id * (length // task_num))
stop = tcps.Scalar(bp.int32, name="stop")

with tcps.for_range(begin = 0, end = loop_num, stage = 1) as i :
    buffer_input = tcps.Buffer(shape=(data_calculated_each_time,), name="input_N", dtype=dtype, scope="nram")
    buffer_target = tcps.Buffer(shape=(data_calculated_each_time,), name="target_N", dtype=dtype, scope="nram")
    buffer_out = tcps.Buffer(shape=(data_calculated_each_time,), name="OUTPUT_N", dtype=dtype, scope="nram")
        
    with tcps.block("data_copy") :
        tcps.memcpy(buffer_input[:data_calculated_each_time], input[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])
        tcps.memcpy(buffer_target[:data_calculated_each_time], target[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])

    with tcps.block("compute") :
        pass
    
    with tcps.block("data_copy") :
        with tcps.if_scope(reduction == 0) :
            tcps.memcpy(out[start + data_calculated_each_time * i:start + data_calculated_each_time * (i+1)], buffer_out[:data_calculated_each_time])

with tcps.if_scope(data_calculated_each_task % data_calculated_each_time != 0):
    start.assign(start + data_calculated_each_time * loop_num)
    stop.assign(start + data_calculated_each_task % data_calculated_each_time)
    #data copy
    tcps.memcpy(buffer_input[:stop-start], input[start:stop])
    tcps.memcpy(buffer_target[:stop-start], target[start:stop]) 
    tcps.divide(buffer_input[:stop-start], buffer_target[:stop-start], buffer_input[:stop-start])
    tcps.log(buffer_input[:stop-start], buffer_input[:stop-start], high_precision = False)
    tcps.multiply(buffer_out[:stop-start], buffer_target[:stop-start], buffer_input[:stop-start])
    tcps.memcpy(out[start:stop], buffer_out[:stop-start])  

f = tcps.BuildBANG(inputs=[input, target, reduction], outputs=[out], kernel_name="kidivloss")

data_input =  np.random.uniform(low=0, high=1, size=(length,))
data_target = np.random.uniform(low=0, high=1, size=(length,)).astype(dtype.as_numpy_dtype)

data_out = np.multiply(data_target, np.log(np.divide(data_target, data_input)))

dev = bp.device(0)

data_input_dev = bp.Array(data_input.astype(dtype.as_numpy_dtype), dev)
data_target_dev = bp.Array(data_target.astype(dtype.as_numpy_dtype), dev)
data_out_dev = bp.Array(np.zeros(data_out.shape, dtype.as_numpy_dtype), dev)

reduction = 0
f(data_input_dev, data_target_dev, reduction, data_out_dev)`

**Comment by Sunshine-KK** [comment]
```
from cmath import e
from bangpy import tcp
from bangpy.tcp.runtime import TaskType
from bangpy.platform.bang_config import TARGET
import bangpy as bp    
import numpy as np

target = "mlu290"
tcps = tcp.TCP(target)

#设置核信息
task_type = TaskType.UNION4
tcps.launch_cluster(task_type.value)
task_num = task_type.value * 4
tcps.launch_task(task_num, 1, 1) 

#设置数据类型和数据个数
dtype = bp.float32
dtype_sz = dtype.bytes
length = 2**31
shape = (length, )

#设置硬件相关信息
compute_row = 32
nram_size = TARGET(target).nram_size 
single_buffer_size = 64 * 128 // dtype.bytes * compute_row

task_id = tcps.taskId

#每次处理的数据量
data_calculated_each_time = single_buffer_size // dtype_sz
data_calculated_each_task  = length // task_num
with tcps.if_scope(task_id == task_num - 1):
    data_calculated_each_task = length // task_num + length % task_num
#每个task需要循环多少次
loop_num = tcps.Scalar(bp.int32, name="loop_num")
loop_num.assign(data_calculated_each_task // data_calculated_each_time)

# global的数据buffer
input = tcps.Buffer(shape=shape, name="input", dtype=dtype, scope="global")
target = tcps.Buffer(shape=shape, name="target", dtype=dtype, scope="global")
out = tcps.Buffer(shape=shape, name="output", dtype=dtype, scope="global")
reduction = tcps.SizeVar(name="reduction")


# 分块处理相关变量
start = tcps.Scalar(bp.int32, name="start")
start.assign(task_id * (length // task_num))
stop = tcps.Scalar(bp.int32, name="stop")

#对于每个task里面的每次buffer计算进行流水线处理
with tcps.for_range(begin = 0, end = loop_num, stage = 1) as i :
    buffer_input = tcps.Buffer(shape=(data_calculated_each_time,), name="input_N", dtype=dtype, scope="nram")
    buffer_target = tcps.Buffer(shape=(data_calculated_each_time,), name="target_N", dtype=dtype, scope="nram")
    buffer_out = tcps.Buffer(shape=(data_calculated_each_time,), name="OUTPUT_N", dtype=dtype, scope="nram")
        
    with tcps.block("data_copy") :
        tcps.memcpy(buffer_input[:data_calculated_each_time], input[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])
        tcps.memcpy(buffer_target[:data_calculated_each_time], target[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])

    with tcps.block("compute") :
        pass
    
    with tcps.block("data_copy") :
        with tcps.if_scope(reduction == 0) :
            tcps.memcpy(out[start + data_calculated_each_time * i:start + data_calculated_each_time * (i+1)], buffer_out[:data_calculated_each_time])

#处理每个task的尾部数据
with tcps.if_scope(data_calculated_each_task % data_calculated_each_time != 0):
    start.assign(start + data_calculated_each_time * loop_num)
    stop.assign(start + data_calculated_each_task % data_calculated_each_time)
    #data copy
    tcps.memcpy(buffer_input[:stop-start], input[start:stop])
    tcps.memcpy(buffer_target[:stop-start], target[start:stop]) 
    tcps.memcpy(out[start:stop], buffer_out[:stop-start])  

f = tcps.BuildBANG(inputs=[input, target, reduction], outputs=[out], kernel_name="kidivloss")


######################################################################################

data_input =  np.random.uniform(low=0, high=1, size=(length,))
data_target = np.random.uniform(low=0, high=1, size=(length,)).astype(dtype.as_numpy_dtype)

data_out = np.multiply(data_target, np.log(np.divide(data_target, data_input)))

dev = bp.device(0)

data_input_dev = bp.Array(data_input.astype(dtype.as_numpy_dtype), dev)
data_target_dev = bp.Array(data_target.astype(dtype.as_numpy_dtype), dev)
data_out_dev = bp.Array(np.zeros(data_out.shape, dtype.as_numpy_dtype), dev)

reduction = 0
f(data_input_dev, data_target_dev, reduction, data_out_dev)

```

**Comment by zhangyicole** [comment]
> ```
> from cmath import e
> from bangpy import tcp
> from bangpy.tcp.runtime import TaskType
> from bangpy.platform.bang_config import TARGET
> import bangpy as bp    
> import numpy as np
> 
> target = "mlu290"
> tcps = tcp.TCP(target)
> 
> #设置核信息
> task_type = TaskType.UNION4
> tcps.launch_cluster(task_type.value)
> task_num = task_type.value * 4
> tcps.launch_task(task_num, 1, 1) 
> 
> #设置数据类型和数据个数
> dtype = bp.float32
> dtype_sz = dtype.bytes
> length = 2**31
> shape = (length, )
> 
> #设置硬件相关信息
> compute_row = 32
> nram_size = TARGET(target).nram_size 
> single_buffer_size = 64 * 128 // dtype.bytes * compute_row
> 
> task_id = tcps.taskId
> 
> #每次处理的数据量
> data_calculated_each_time = single_buffer_size // dtype_sz
> data_calculated_each_task  = length // task_num
> with tcps.if_scope(task_id == task_num - 1):
>     data_calculated_each_task = length // task_num + length % task_num
> #每个task需要循环多少次
> loop_num = tcps.Scalar(bp.int32, name="loop_num")
> loop_num.assign(data_calculated_each_task // data_calculated_each_time)
> 
> # global的数据buffer
> input = tcps.Buffer(shape=shape, name="input", dtype=dtype, scope="global")
> target = tcps.Buffer(shape=shape, name="target", dtype=dtype, scope="global")
> out = tcps.Buffer(shape=shape, name="output", dtype=dtype, scope="global")
> reduction = tcps.SizeVar(name="reduction")
> 
> 
> # 分块处理相关变量
> start = tcps.Scalar(bp.int32, name="start")
> start.assign(task_id * (length // task_num))
> stop = tcps.Scalar(bp.int32, name="stop")
> 
> #对于每个task里面的每次buffer计算进行流水线处理
> with tcps.for_range(begin = 0, end = loop_num, stage = 1) as i :
>     buffer_input = tcps.Buffer(shape=(data_calculated_each_time,), name="input_N", dtype=dtype, scope="nram")
>     buffer_target = tcps.Buffer(shape=(data_calculated_each_time,), name="target_N", dtype=dtype, scope="nram")
>     buffer_out = tcps.Buffer(shape=(data_calculated_each_time,), name="OUTPUT_N", dtype=dtype, scope="nram")
>         
>     with tcps.block("data_copy") :
>         tcps.memcpy(buffer_input[:data_calculated_each_time], input[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])
>         tcps.memcpy(buffer_target[:data_calculated_each_time], target[start + data_calculated_each_time * i: start + data_calculated_each_time * (i+1)])
> 
>     with tcps.block("compute") :
>         pass
>     
>     with tcps.block("data_copy") :
>         with tcps.if_scope(reduction == 0) :
>             tcps.memcpy(out[start + data_calculated_each_time * i:start + data_calculated_each_time * (i+1)], buffer_out[:data_calculated_each_time])
> 
> #处理每个task的尾部数据
> with tcps.if_scope(data_calculated_each_task % data_calculated_each_time != 0):
>     start.assign(start + data_calculated_each_time * loop_num)
>     stop.assign(start + data_calculated_each_task % data_calculated_each_time)
>     #data copy
>     tcps.memcpy(buffer_input[:stop-start], input[start:stop])
>     tcps.memcpy(buffer_target[:stop-start], target[start:stop]) 
>     tcps.memcpy(out[start:stop], buffer_out[:stop-start])  
> 
> f = tcps.BuildBANG(inputs=[input, target, reduction], outputs=[out], kernel_name="kidivloss")
> 
> 
> ######################################################################################
> 
> data_input =  np.random.uniform(low=0, high=1, size=(length,))
> data_target = np.random.uniform(low=0, high=1, size=(length,)).astype(dtype.as_numpy_dtype)
> 
> data_out = np.multiply(data_target, np.log(np.divide(data_target, data_input)))
> 
> dev = bp.device(0)
> 
> data_input_dev = bp.Array(data_input.astype(dtype.as_numpy_dtype), dev)
> data_target_dev = bp.Array(data_target.astype(dtype.as_numpy_dtype), dev)
> data_out_dev = bp.Array(np.zeros(data_out.shape, dtype.as_numpy_dtype), dev)
> 
> reduction = 0
> f(data_input_dev, data_target_dev, reduction, data_out_dev)
> ```

该部分代码的shape定义为(2**31,)，已经超出int32的表示范围了。我尝试修改为(2**30,)，是没有问题的
