### ISSUE TITLE
能详细解释一下Bufferslice的用法以及和memcpy的组合吗

### ISSUE THREAD

**Issue by cnzjyjp** [Cambricon/mlu-ops#29]
![微信截图_20220430162306](https://user-images.githubusercontent.com/37297476/166098099-0d2d51e9-c4c2-4231-a6b8-c4c41c35a934.png)
Guide里面的Bufferslice的用法感觉没有写的很具体，不知道怎么用参数n,h,w,c定义一个切片；

具体来说，对于GDRAM上的一个一维Buffer，我想要每隔L个元素取连续的K个元素（从第0个开始先取K个，然后每隔L个取K个），假设总共要取M个，能否将这M个元素通过Bufferslice的方法用一个memcpy语句将它们连续存储到NRAM上的一个长度为M个元素的buffer中呢？如果能的话**麻烦教一下参数应该怎么设置**（n,h,w,c,valid_dim）。
因为如果用一般的memcpy，一次能操作的元素上限就被K限制住了，会导致效率很低。所以想知道Bufferslice能否解决我的问题，谢谢。

**Comment by stuart-yang** [comment]
关于切片操作，可以参考python中的切片操作，一般切片操作是针对已有形状的Tensor完成的，比如（n，h，w，c），可以选择h上的切片，将w和c上的数据取出。对于一维buffer的切片写法，当前版本没有step不为1的，马上发布的BANGPy1.4.0会支持这个step不为1的情况，但不能完成上面的例子。所以，将buffer reshape成一定的形状，再尝试用切片操作。

**Comment by stuart-yang** [comment]
一起讨论： 如果在一维的buffer上使用带stride的memcpy的话，和pyhton接口的设计目标是不一致的。使用切片操作的优点就是利用对tensor的操作，将tensor用一维的方式处理，就相似于C对array的编程，引进这样的方式不难，但是会将这样的用法和切片的用法混淆起来，使用起来也会更复杂，不利于提供一个易用简明的语言环境。

**Comment by cnzjyjp** [comment]
@stuart-yang python的切片操作不是类似于L[start:stop:step]吗，nhwc是类似图像处理的那个nhwc吗，是不是要对tensor做一些处理？
就是我的需求是对于一个Tensor，可以reshape成(group,3,step)，我想要将(tensor[0][0][0:step],tensor[1][0][0:step],tensor[2][0][0:step],…)memcpy到一个nram的buffer上，(tensor[0][1][0:step],tensor[1][1][0:step],tensor[2][1][0:step],…)到另一个buffer上，flatten成一维就是每隔2*step的step个元素是一组的，就是想问能不能用Bufferslice或者其他方式，用一个memcpy实现将buffer可以容纳的组数一次全部填进去？因为如果分次的话，step很小的情况下要填充一个buffer需要很多次memcpy，效率就会很低。
希望可以帮忙解决这个瓶颈，谢谢！

**Comment by cnzjyjp** [comment]
![微信截图_20220505163941](https://user-images.githubusercontent.com/37297476/166889337-30d39884-643a-455b-ad5b-2f1b6d83990f.png)
![微信截图_20220505164022](https://user-images.githubusercontent.com/37297476/166889342-246f2411-e256-485d-8bb5-3bcc738f026b.png)
我刚刚尝试了如上的切片方式进行memcpy，貌似是您提到的step不支持不为1的问题，如果支持step不为1的话我应该可以得到想要的结果：
![微信截图_20220505164355](https://user-images.githubusercontent.com/37297476/166889845-7f79fcca-38c2-476a-9049-9d630d7efa74.png)

请问我们什么时候可以在云主机上用BANGPy1.4.0做开发呢？

**Comment by cnzjyjp** [comment]
报错信息，应该是step不支持不为1：
![微信截图_20220505164527](https://user-images.githubusercontent.com/37297476/166890071-91c713a0-8fa7-4f80-89e5-3b43d230d61f.png)

**Comment by stuart-yang** [comment]
上面的实验挺好，目前1.4.0 正在提测，应该很快能用上，理想情况是本周。

**Comment by cnzjyjp** [comment]
好的谢谢，希望云平台的BANGPy可以跟进1.4.0版本
