### ISSUE TITLE
BANGPy1.4.0的Buffer切片要如何和memcpy结合使用？

### ISSUE THREAD

**Issue by cnzjyjp** [Cambricon/mlu-ops#36]
在流水线中使用如下指令编译会不通过：
![微信截图_20220513163938](https://user-images.githubusercontent.com/37297476/168245656-41ed57f9-4a3c-4d25-9bce-700e0d0dea37.png)
![微信截图_20220513164001](https://user-images.githubusercontent.com/37297476/168245671-82d48294-0371-4232-9929-450455a28524.png)
请问有办法可以在流水线里将一个GDRAM上的切片flatten然后拷贝到nram的一维Buffer上吗？
因为GDRAM的维度大小在编译前是不可知的，所以也没有办法创建一个和GDRAM切片形状相同的nram上的buffer。

**Comment by SYangDong** [comment]
这个看报错是越界了吧，比较简单的可以reshape一下，变成[n ,3] 然后分别取[:, 1], [:2,], [:3], 不需要faltten试试

**Comment by cnzjyjp** [comment]
@SYangDong 
这个是strided copy，就是我是想对于buffer_in0[x:y]从x=start到x=stop为止每3个拷贝y个数据到buffer_a0里，例如buffer_in0[0][0:y],buffer_in0[3][0:y],buffer_in0[6][0:y],……用一个memcpy来完成操作。
不知道你的意思是否是改成每次拷贝y个元素？但是我的问题就是在y很小的时候一次memcpy只能拷贝很小的元素，导致效率很低。

**Comment by zhangyicole** [comment]
能push一份完整的代码吗？这里的报错是slice里的start+step超出了stop，也即越界。start_ping和stop_ping的值是多少，能看下吗？

**Comment by cnzjyjp** [comment]
@zhangyicole 好的，我先自己检查一下是否发生越界，谢谢

**Comment by cnzjyjp** [comment]
@zhangyicole 
我用简单的例子测试还是报错，打印出来也没有越界，现在我改成这样的固定值还是报错，虽然报错信息变了，请问是否是BANGPy1.4.0仍然不支持这种操作呢：
![微信截图_20220516163153](https://user-images.githubusercontent.com/37297476/168551881-70a97ccc-481d-4db7-9607-896b4368e5c5.png)
![微信截图_20220516163037](https://user-images.githubusercontent.com/37297476/168551950-55f0d21c-6241-47d2-b196-81be9a27d524.png)
![微信截图_20220516163103](https://user-images.githubusercontent.com/37297476/168551958-c43f859a-2d78-45ff-961f-2ac33aac568b.png)
这条语句时buffer_in0的shape是(6,20)，buffer_a0是一个足够大的一维Buffer。我想要用strided copy，选中的内容是buffer_in0[0][0:20]+buffer_in0[3][0:20]。

**Comment by cnzjyjp** [comment]
完整报错信息：
![微信截图_20220516163816](https://user-images.githubusercontent.com/37297476/168553019-73239344-c6e2-415d-b315-4d1bb2b389cf.png)

**Comment by zhangyicole** [comment]
https://github.com/Cambricon/mlu-ops/issues/36#issue-1234920919 里的问题是在使用slice的时候，使用了scalar做slice参数，在使用scalar做参数的时候，麻烦使用scalar.get()接口，将scalar的value取出 再作为参数，在你的例子里，就是写为memcpy(buffer_in0[start_ping.get():stop_ping.get():3])。
https://github.com/Cambricon/mlu-ops/issues/36#issuecomment-1127388908 里的问题是flattern接口必须作用在一个数据连续的buffer上，你的buffer_in[]

**Comment by cnzjyjp** [comment]
@zhangyicole 好的谢谢，刚刚试了一下strided copy是可行的，希望后续BANGPy能支持一下不连续buffer的flatten就更好了，python里应该是可以对不连续buffer做flatten的，比如b=a[0:5:3].flatten()

**Comment by cnzjyjp** [comment]
step是跟输入样例有关的变量值，所以流水线的Buffer还是要先定义再reshape。是否还是跟不连续的Buffer有关？memcpy的两个buffer都必须是连续的吗？

**Comment by cnzjyjp** [comment]
step是跟输入样例有关的变量值，所以流水线的Buffer还是要先定义再reshape。

**Comment by zhangyicole** [comment]
这个报错是地址越界了，应该是拷贝偏移的有问题，麻烦放一份完整的代码，才能调试出问题。

**Comment by cnzjyjp** [comment]
@zhangyicole 好的谢谢，我再详细测一下每个变量的值，因为完整代码的内容比较多先不麻烦了，我再算一下哪里越界了

**Comment by zhangyicole** [comment]
可以push一份分支上来的

**Comment by cnzjyjp** [comment]
@zhangyicole  已经查出问题了，谢谢！
