### ISSUE TITLE
bangpy打印不全

### ISSUE THREAD

**Issue by Alaskra** [Cambricon/mlu-ops#42]
有些时候bangpy打印不全，调试的时候比较麻烦，请问有什么解决办法吗
![image](https://user-images.githubusercontent.com/49367127/168992520-4b46be85-9cea-4d5c-8810-36c24ecbf9ba.png)

**Comment by zhangyicole** [comment]
请通过设置CNRT_BANGC_PRINTF_LIMIT环境变量的值来设置可打印的最大字节数，默认为1024B。

**Comment by Alaskra** [comment]
试了下确实可以，谢谢
