### ISSUE TITLE
关于IMM for u32 out of range的warning以及大数据情况下才会出现的错误

### ISSUE THREAD

**Issue by cnzjyjp** [Cambricon/mlu-ops#43]
![微信截图_20220518215424](https://user-images.githubusercontent.com/37297476/169057640-17415037-1145-4efd-ad02-dbd0381c216c.png)
数据量大的时候出现上面的warning会对程序正常执行有影响吗？意思是立即数有超过unsigned int32表示范围的意思吗？

在数据量大到出现上面warning的时候，对于下面的代码：
![微信截图_20220518215608](https://user-images.githubusercontent.com/37297476/169058482-e3a09953-fb43-4b61-867a-47d8099a9a41.png)
如果我没有红框内的这部分代码程序会正常执行，但是结果会有0.01%的错误（数据量再小一点比如0.5倍就全对pass）；
如果加上这部分代码（最后一次循环i=255），会直接报以下错误：
![微信截图_20220518215639](https://user-images.githubusercontent.com/37297476/169059723-9f1302ef-31da-4568-8db0-38404af68732.png)
请问这是否和out of range有关呢？

**Comment by cnzjyjp** [comment]
数据规模是9*(2**27)

**Comment by zhangyicole** [comment]
麻烦给完整的代码，才能知道原因，单从现有报错信息看不出原因。warning是正常的编译提示，对程序无影响。

**Comment by cnzjyjp** [comment]
@zhangyicole 这样传可以吗
[cross_1.zip](https://github.com/Cambricon/mlu-ops/files/8717327/cross_1.zip)

**Comment by cnzjyjp** [comment]
在test中有两个例子，都是数据规模大到一定程度就出现问题的，小一点就可以通过，麻烦帮忙看一下

**Comment by cnzjyjp** [comment]
test文件有一点错误，重传了一份
[cross_1.zip](https://github.com/Cambricon/mlu-ops/files/8717372/cross_1.zip)

**Comment by cnzjyjp** [comment]
test文件有一点错误，重新传了一份
[cross_1.zip](https://github.com/Cambricon/mlu-ops/files/8717381/cross_1.zip)

**Comment by cnzjyjp** [comment]
发现分支1情况的两个test都是过不了的，现在测试((1,512,1,1,3,1,1,1452),4)能过，((1,512,1,1,3,1,1,1453),4)就出现数据不相等了

**Comment by cnzjyjp** [comment]
已经发现问题并且解决了，麻烦了
分支2存在的问题如果没解决会重新发一个issue

**Comment by zhangyicole** [comment]
我在调试的时候，发现，你的代码还是有越界。在1022次循环的时候，leap1_ping已经小于start_ping了。

**Comment by cnzjyjp** [comment]
@zhangyicole 非常感谢，分支2的情况确实是还有问题的，我也正在调试，谢谢！
