### ISSUE TITLE
memcpy报错但是检查坐标值都没有问题

### ISSUE THREAD

**Issue by cnzjyjp** [Cambricon/mlu-ops#44]
[cross1.zip](https://github.com/Cambricon/mlu-ops/files/8747094/cross1.zip)
提供的代码如上，在if分支2的流水线中打开所有的memcpy，运行测试用例，报错如下：
![微信截图_20220521143615](https://user-images.githubusercontent.com/37297476/169639258-f16d20cd-2ee7-4662-9d55-dc37b28b388d.png)
注释掉部分代码，并且检查buffer坐标是否有问题（见cross_越界.py）：
![微信截图_20220521143737](https://user-images.githubusercontent.com/37297476/169639303-ddf0e37b-c4a8-437a-b052-71b052276a04.png)
还是报错，且没有打印出任何预设的信息；

注释掉所有的memcpy并且检查buffer坐标是否有问题（见cross_无Error.py）：
![微信截图_20220521143918](https://user-images.githubusercontent.com/37297476/169639333-9f717b25-bb05-43b4-9d48-b379ece8171b.png)
test通过，且没有打印出任何预设的信息。

而且是对于一个特定的较大测试用例会出错，规模稍小的样例全都能pass（见test_cross.py）。
麻烦能帮忙找一下问题出在哪里吗？

**Comment by zhangyicole** [comment]
这里应该是只要打开流水，代码就完全错误。因为你的load的datacopy stmt里面有标量运算，同时你的这部分标量运算的结果又会作用到store的datacopy stmt，就是产生了数据依赖，流水是错误的。流水的代码需要重新设计，比如把标量操作改成长度为1的向量buffer的load，store操作，同时把这些buffer写到pipeline stage之下，让其产生正确的流水。

**Comment by cnzjyjp** [comment]
@zhangyicole 请问为什么会有数据依赖呢?
按照我的理解，BANGPy的流水分为ping和pong两部分，假设首先是ping开始，那么ping先load(i=0)；然后ping进入compute(i=0)，pong进入load(i=1)；然后pong进入compute(i=1)，ping先store(i=0)然后load(i=2)；……
那么ping和pong只有一个会处在compute，另外一个则处于load/store，那么对标量的赋值只在load阶段进行一次，当ping在load时，pong必然在compute阶段对整个nram做不涉及坐标的计算操作；其次，按照我的代码每次循环对start等变量的赋值只会发生一次，然后使用的标量xx_ping/pong都是xx的一个副本，如果我只在load做一次赋值，那么相当于xx_ping/pong是和循环的i绑定的，而且ping在修改/读取start和leap1的时候pong不可能在修改/读取这些值呀?为什么会有数据依赖呢？
请问我对流水线理解有没有问题？
最关键的，如果是因为数据依赖，那么为什么只有数据量达到这个规模时才会出错呢?如果因为数据依赖产生了坐标值与预期不符的情况，为什么我设置的越界检查都没有打印出信息呢？如果没有越界也应该是结果出错而不是运行出错呀。
谢谢

**Comment by cnzjyjp** [comment]
我先试一下您说的把标量存到Buffer里面

**Comment by cnzjyjp** [comment]
@zhangyicole 按您的意见用buffer来存储标量
[cross_buffer.zip](https://github.com/Cambricon/mlu-ops/files/8779489/cross_buffer.zip)
仅先对start,leap1,leap2进行存储报如下错误（任意规模的测试用例都报）：
![微信截图_20220526204038](https://user-images.githubusercontent.com/37297476/170502419-65a4ffcf-5b28-43c8-8f87-f80fe5607f87.png)
调试了一下也没有找到错误，请问是我load和store的方法不对吗

**Comment by cnzjyjp** [comment]
[cross_flag_buffer.zip](https://github.com/Cambricon/mlu-ops/files/8779660/cross_flag_buffer.zip)
对flag也用buffer进行存储以后，所有样例都报上面的unknown error

**Comment by zhangyicole** [comment]
该问题是否还存在呢？ @cnzjyjp

**Comment by cnzjyjp** [comment]
@zhangyicole 还没有解决，但是我觉得大概率应该是数据规模太大导致了一些问题，现在正在将Bangpy1的代码重构到Bangpy2的script形式，重构完如果还有问题再看看。
