### ISSUE TITLE
bangpy中buffer align检查的问题

### ISSUE THREAD

**Issue by Alaskra** [Cambricon/mlu-ops#46]
![image](https://user-images.githubusercontent.com/49367127/169983138-d4a470dc-e3b8-43db-a734-76f823d85d2c.png)
这里的`buffer_out_n`等变量都是nram上float32数据类型，所以`buffer_out_n[:32]`的size应该是128byte吧，为什么报错中说是64byte呢？

**Comment by zhangyicole** [comment]
感谢指出，这里的报错信息有误，是这条指令的元素个数必须64对齐，而不是字节数。

**Comment by Alaskra** [comment]
还有就是bangpy文档写的也有问题，文档里说这个maximum函数要求128 byte align

**Comment by zhangyicole** [comment]
该问题已修复。
