### ISSUE TITLE
bangpy：这样使用muladd有什么问题吗

### ISSUE THREAD

**Issue by Alaskra** [Cambricon/mlu-ops#48]
![image](https://user-images.githubusercontent.com/49367127/170044780-15821b1a-3fb0-47d8-a292-c9b2f75b7c85.png)
我想用muladd来替换上面注释掉的两行，结果报错了。之前是编译运行通过的。请问哪里出了问题？

**Comment by zhangyicole** [comment]
muladd指令在你们使用的290架构上暂不支持，这里我们有问题，后续会加强架构检查。文档里有说明这个指令的限制吗？

**Comment by Alaskra** [comment]
文档里没有说架构的限制。

**Comment by Alaskra** [comment]
还有请问使用muladd指令和使用mul+add两条指令有什么区别吗，比如性能会更快什么的

**Comment by SYangDong** [comment]
性能会更好
