### ISSUE TITLE
readme中cntoolkit和bangpy内容改进

### ISSUE THREAD

**Issue by coffeez** [Cambricon/mlu-ops#516]
`sudo apt-get install cncc cnas cnbin cndrv cnrt cnrtc` 最好改为 `sudo get-get install cntoolkit-cloud` ，`cntoolkit-cloud` 和 `cntoolkit-edge` 是2个meta包，可以自动安装所有依赖包，而且会生成`/usr/local/neuware/version.txt`，version.txt会被用来做cntoolkit的版本号检查。

bangpy不维护了，可以删除了。

**Comment by duzekunKTH** [comment]
感谢建议！根据仓库规划与维护规范，bangpy 将会在 x 版本升级时移除。
