### ISSUE TITLE
[New Op] R-FCN - roi_crop 算子开发

### ISSUE THREAD

**Issue by WangYuan-cn** [Cambricon/mlu-ops#59]
* 算子名称：roi_crop
* 应用网络：R-FCN
* 参考实现：https://github.com/princewang1994/R-FCN.pytorch/tree/master/lib/model/roi_crop

**Comment by tudejiang79** [comment]
[PR #51](https://github.com/Cambricon/mlu-ops/pull/51)

**Comment by WangYuan-cn** [comment]
Done
