### ISSUE TITLE
[New Op] Faster R-CNN trans OBB - poly_nms 算子开发

### ISSUE THREAD

**Issue by WangYuan-cn** [Cambricon/mlu-ops#61]
- 算子名称：poly_nms
- 应用网络：Faster R-CNN trans OBB
- 参考实现：https://github.com/dingjiansw101/AerialDetection/blob/master/mmdet/ops/poly_nms/src/poly_nms_kernel.cu

**Comment by guzhonghao** [comment]
[CNNLCORE-6878]feat(poly_nms):add op design doc.  #63

**Comment by guzhonghao** [comment]
算子合入： https://github.com/Cambricon/mlu-ops/pull/97

**Comment by guzhonghao** [comment]
poly_nms generavator  PR: https://github.com/Cambricon/mlu-ops-generator/pull/11
