### ISSUE TITLE
GDRAM到SRAM如何并行拷贝内存

### ISSUE THREAD

**Issue by Edward1900** [Cambricon/mlu-ops#74]
__memcpy(input1SRAM+taskId* k, input1DDR+taskId* k,k * sizeof(int8_t), GDRAM2SRAM);  
如果是MLU220,这里使用是否正确,

**Comment by SYangDong** [comment]
这里面应该不会涉及到taskId， 因为GDRAM和SRAM都是全局访问

**Comment by zhangyicole** [comment]
这种写法是错误的，SRAM是单cluster全局访问。

**Comment by zhangyicole** [comment]
这种写法是错误的，SRAM是单cluster全局访问，taskId在这里应该不会起作用，如果是UNION1任务，那么taskId的值这里应该会为0(与单cluster上的第0个ipu core的taskId相同)。

**Comment by Edward1900** [comment]
> 这里面应该不会涉及到taskId， 因为GDRAM和SRAM都是全局访问

感谢回复，我想 GDRAM并行向SRAM进行拷贝，该怎么做呢？单次拷贝在多次循环中太慢了

**Comment by zhangyicole** [comment]
> > 这里面应该不会涉及到taskId， 因为GDRAM和SRAM都是全局访问
> 
> 感谢回复，我想 GDRAM并行向SRAM进行拷贝，该怎么做呢？单次拷贝在多次循环中太慢了

能具体描述一下并行拷贝的意思吗？GDRAM2SRAM的拷贝应该不存在并行，每个cluster的拷贝只有一个控制系统来控制。

**Comment by zhangyicole** [comment]
> 就像多核并行计算一样，我们希望内存也可以并行memcpy，因为发现循环次数过大内存操作这部分将非常耗时
请问是同一方向还是不同方向的memcpy的并行呢？同一方向走的同一通道，本来就是并行的，不同方向的话，视情况而定，可以使用自动流水的方式来进行不同通道上的memcpy的并行。

**Comment by Edward1900** [comment]
> > 就像多核并行计算一样，我们希望内存也可以并行memcpy，因为发现循环次数过大内存操作这部分将非常耗时
> > 请问是同一方向还是不同方向的memcpy的并行呢？同一方向走的同一通道，本来就是并行的，不同方向的话，视情况而定，可以使用自动流水的方式来进行不同通道上的memcpy的并行。

感谢回复，是同一方向的GDRAM2SAM。
再请教另外一个问题：SAM2SAM为什么报错如下：
   __mlu_shared__ int8_t input1SRAM[256*1024];
   __mlu_shared__ int8_t input2SRAM[256*1024];

./gemm_CONV.mlu:399:9: error: invalid direction '23' for function ''__memcpy''
        __memcpy(input1SRAM+m*k, input2SRAM+w_start,(w_end-w_start)*ci*sizeof(int8_t), SRAM2SRAM, kw*ci* sizeof(int8_t), wi*ci* sizeof(int8_t), (h_end-h_s...
        ^                                                                              ~~~~~~~~~
./gemm_CONV.mlu:399:9: error: invalid pointer address space '__mlu_shared__' for '__memcpy', expected '__mlu_device__'
        __memcpy(input1SRAM+m*k, input2SRAM+w_start,(w_end-w_start)*ci*sizeof(int8_t), SRAM2SRAM, kw*ci* sizeof(int8_t), wi*ci* sizeof(int8_t), (h_end-h_s...
        ^        ~~~~~~~~~~~~~~
2 errors generated.

**Comment by zhangyicole** [comment]
> > > 就像多核并行计算一样，我们希望内存也可以并行memcpy，因为发现循环次数过大内存操作这部分将非常耗时
> > > 请问是同一方向还是不同方向的memcpy的并行呢？同一方向走的同一通道，本来就是并行的，不同方向的话，视情况而定，可以使用自动流水的方式来进行不同通道上的memcpy的并行。
> 
> 感谢回复，是同一方向的GDRAM2SAM。 再请教另外一个问题：SAM2SAM为什么报错如下： **mlu_shared** int8_t input1SRAM[256_1024]; **mlu_shared** int8_t input2SRAM[256_1024];
> 
> ./gemm_CONV.mlu:399:9: error: invalid direction '23' for function ''__memcpy'' __memcpy(input1SRAM+m_k, input2SRAM+w_start,(w_end-w_start)_ci_sizeof(int8_t), SRAM2SRAM, kw_ci* sizeof(int8_t), wi_ci_ sizeof(int8_t), (h_end-h_s... ^ ~~~~~~~~~ ./gemm_CONV.mlu:399:9: error: invalid pointer address space '**mlu_shared**' for '__memcpy', expected '**mlu_device**' __memcpy(input1SRAM+m_k, input2SRAM+w_start,(w_end-w_start)_ci_sizeof(int8_t), SRAM2SRAM, kw_ci* sizeof(int8_t), wi_ci_ sizeof(int8_t), (h_end-h_s... ^ ~~~~~~~~~~~~~~ 2 errors generated. ![image](https://user-images.githubusercontent.com/38486610/174233121-6263af1b-e287-4b50-8255-2c6d2657b1fb.png)

__mlu_shared__，不是mlu_shared__

**Comment by Edward1900** [comment]
> 

貌似找到问题，高版本CNToolkit可编译成功，以上错误发生在 Neuware Version 1.3.0

**Comment by Edward1900** [comment]
> > > > 就像多核并行计算一样，我们希望内存也可以并行memcpy，因为发现循环次数过大内存操作这部分将非常耗时
> > > > 请问是同一方向还是不同方向的memcpy的并行呢？同一方向走的同一通道，本来就是并行的，不同方向的话，视情况而定，可以使用自动流水的方式来进行不同通道上的memcpy的并行。
> > 
> > 
> > 感谢回复，是同一方向的GDRAM2SAM。 再请教另外一个问题：SAM2SAM为什么报错如下： **mlu_shared** int8_t input1SRAM[256_1024]; **mlu_shared** int8_t input2SRAM[256_1024];
> > ./gemm_CONV.mlu:399:9: error: invalid direction '23' for function ''__memcpy'' __memcpy(input1SRAM+m_k, input2SRAM+w_start,(w_end-w_start)_ci_sizeof(int8_t), SRAM2SRAM, kw_ci* sizeof(int8_t), wi_ci_ sizeof(int8_t), (h_end-h_s... ^ ~~~~~~~~~ ./gemm_CONV.mlu:399:9: error: invalid pointer address space '**mlu_shared**' for '__memcpy', expected '**mlu_device**' __memcpy(input1SRAM+m_k, input2SRAM+w_start,(w_end-w_start)_ci_sizeof(int8_t), SRAM2SRAM, kw_ci* sizeof(int8_t), wi_ci_ sizeof(int8_t), (h_end-h_s... ^ ~~~~~~~~~~~~~~ 2 errors generated. ![image](https://user-images.githubusercontent.com/38486610/174233121-6263af1b-e287-4b50-8255-2c6d2657b1fb.png)
> 
> 能push一份完整的代码吗？从给出的两行代码看，应该是没有问题的。

貌似找到问题，高版本CNToolkit可编译成功，以上错误发生在 Neuware Version 1.3.0

**Comment by Edward1900** [comment]
@zhangyicole  您好，再次请教，我现在使用mlu270编译bangc-ops成功，
但测试出问题：./mluop_gtest --gtest_filter=*abs*

root@localhost:~/test/mlu-ops/bangc-ops/build/test# ./mluop_gtest --gtest_filter=*abs*
Note: Google Test filter = *abs*
[==========] Running 1 test case from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from abs/TestSuite
[2022-6-17 15:5:8] [MLUOP] [Error]:[mluOpCreate] An internal error occured.   [ /root/test/mlu-ops/bangc-ops/core/context.cpp:127  pid:108423]
/root/test/mlu-ops/bangc-ops/test/mlu_op_gtest/include/executor.h:110: Failure
Expected equality of these values:
  mluOpCreate(&handle)
    Which is: 4
  MLUOP_STATUS_SUCCESS
    Which is: 0
[ RUN      ] abs/TestSuite.mluOp/0
2022-06-17 07:05:08.021747: [cnrtError] [108423] [Card : 0] cnrtPlaceNotifier: Input argument 'notifier' is NULL. Please check this argument.
/root/test/mlu-ops/bangc-ops/test/mlu_op_gtest/src/executor.cpp:101: Failure
Failed
Check failed: CNRT_RET_SUCCESS == cnrtPlaceNotifier(exe_context_->n_start, exe_context_->queue). 
[2022-6-17 15:5:8] [MLUOP] [Warning]:Executor: reset cnrt and go on running, this may caused by cnrt failed.  [ /root/test/mlu-ops/bangc-ops/test/mlu_op_gtest/include/executor.h:137  pid:108423]
[2022-6-17 15:5:8] [MLUOP] [Error]:[mluOpCreate] An internal error occured.   [ /root/test/mlu-ops/bangc-ops/core/context.cpp:127  pid:108423]
/root/test/mlu-ops/bangc-ops/test/mlu_op_gtest/include/executor.h:110: Failure
Expected equality of these values:
  mluOpCreate(&handle)
    Which is: 4
  MLUOP_STATUS_SUCCESS
    Which is: 0
/root/test/mlu-ops/bangc-ops/test/mlu_op_gtest/src/gtest/mlu_op_gtest.cpp:96: Failure
Failed
MLUOP GTEST: catched /root/test/mlu-ops/bangc-ops/test/mlu_op_gtest/src/executor.cpp +101 in single thread mode. (of ../../test/mlu_op_gtest/src/zoo/abs/test_case/case_0.prototxt)

[MLU Hardware Time     ]: -1 (us)
[MLU Interface Time    ]: -1 (us)
[MLU IO Efficiency     ]: -1
[MLU Compute Efficiency]: -1
[MLU Workspace Size    ]: -1 (Bytes)
[MLU TheoryOps         ]: -1 (Ops)
[MLU TheoryIOs         ]: -1 (Bytes)
[MLU ComputeForce      ]: -1 (op/s)
[MLU IoBandWidth       ]: -1 (GB/s)
Unknown error: maybe exception raised, other info is lost.
[^  FAILED ] ../../test/mlu_op_gtest/src/zoo/abs/test_case/case_0.prototxt
/root/test/mlu-ops/bangc-ops/test/mlu_op_gtest/src/gtest/mlu_op_gtest.cpp:379: Failure
Value of: passed
  Actual: false
Expected: true
[  FAILED  ] abs/TestSuite.mluOp/0, where GetParam() = ("abs", 0) (5 ms)
[----------] 1 test from abs/TestSuite (5 ms total)

[----------] Global test environment tear-down
[ SUMMARY  ] Total 1 cases of 1 op(s).
1 CASES FAILED:
Failed: ../../test/mlu_op_gtest/src/zoo/abs/test_case/case_0.prototxt
[==========] 1 test case from 1 test suite ran. (45 ms total)
[  PASSED  ] 0 test cases.
[  FAILED  ] 1 test case, listed below:
[  FAILED  ] abs/TestSuite.mluOp/0, where GetParam() = ("abs", 0)

 1 FAILED TEST

这个错误是什么原因？

我查看了驱动：
Device name: MLU270-V4
Device inode path: /dev/cambricon_dev3
Device Major: 231
Device Minor: 3
Driver Version: v4.2.0
MCU Version: v1.1.3
Board Serial Number: SN/141909101917
MLU Firmware Version: 4.2.0
Board CV: 0

这个问题是否跟驱动版本太低有关？

**Comment by zcyKTH** [comment]
> 

疑似是driver版本问题，当前镜像中CNToolkit的版本对应的驱动最好是4.15.12以上的版本
