### ISSUE TITLE
BANGC-OPS算子开发流程的内容与实际代码仓库不一致

### ISSUE THREAD

**Issue by LiuzengQ-Q** [Cambricon/mlu-ops#743]
BANGC-OPS算子开发流程的内容与实际代码仓库不一致。
例如：1. 文档开发阶段以 add 算子为例，但是docs/bangc-docs/design_docs/ 目录下并没有 add.md，kernels/ 目录下也没有 add算子代码文件夹。

**Comment by PetrelYy** [comment]
当前仓库中算子分为通用、长尾（领域类）两类：
1. 前者由单独的内部仓库进行支持（暂未开源），mlu-ops 以二进制形式集成了这些算子，涉及算子可见 mlu-ops/bangc-ops/kernels/kernel_wrapper/wrapper.h
2. 学习阶段建议参考：

> mlu-ops/docs/bangc-docs/BANGC-OPS-Operator-Development-Process.md
> abs 或其他领域类算子，mlu-ops/bangc-ops/kernels/abs/abs_block.mlu



非常感谢您的问题，后续仓库中将补充对上述两类算子说明

**Comment by duzekunKTH** [comment]
@LiuzengQ-Q 上述回复能否解答您提出的问题？

**Comment by LiuzengQ-Q** [comment]
行吧，我反正看源码看得很头疼发自我的 iPhone在 2023年7月28日，16:46，duzekun ***@***.***> 写道：﻿
@LiuzengQ-Q 上述回复能否解答您提出的问题？

**Comment by PetrelYy** [comment]
后续我们会使用仓内其他简单算子作为举例，保证BANGC-OPS算子开发流程的内容与实际代码仓库一致。
待修改完成后，会在此 Issue 中通知您。
对于上一次给您的回复，误以为您对仓库内 addN 算子有疑问，所以给出基于 addN 算子可参考的开发指导。

**Comment by Unireverse** [comment]
您好，感谢您的反馈，请问我们的回复是否解答了您的疑问？

**Comment by LiuzengQ-Q** [comment]
感谢你们的回复。已经解答了我的疑问。发自我的 iPhone在 2023年9月1日，17:28，Chengwei Dong ***@***.***> 写道：﻿
您好，感谢您的反馈，请问我们的回复是否解答了您的疑问？

**Comment by chqy99** [comment]
再次感谢您的提问。针对您提出的问题，我们在PR（https://github.com/Cambricon/mlu-ops/pull/800）中做了相应的修改。我们真诚地感谢您对MLU-OPS社区的贡献，也诚挚地邀请您提出更多建议，帮助我们的社区变得更好。祝好！
