### ISSUE TITLE
关于strided memcpy

### ISSUE THREAD

**Issue by shiiiivering** [Cambricon/mlu-ops#77]
由于数据对齐的需要，有时候我们需要将原本形状为(N, 31)的数据转变为(N, 32)的形状去处理，因此采用如下拷贝模式：
```python
input_g_buffer = tcp.Buffer(shape = (data_N, 31))
tcp.memcpy(input_n_buffer.reshape((N, 32))[:N, :31], input_g_buffer[base : base + N])
```
这种情况下，由于非连续拷贝，IO效率会有一个较显著的降低。但是当我使用这种写法进行对齐数据的计算时：
```python
input_g_buffer = tcp.Buffer(shape = (data_N, 32))
tcp.memcpy(input_n_buffer.reshape((N, 32))[:N, :32], input_g_buffer[base : base + N])
```
效率也会有较大的降低。没用切片的写法时就能恢复正常的IO效率。

**Comment by SYangDong** [comment]
这个代码感觉不太对， tcp.memcpy(input_n_buffer.reshape((N, 32))[:N, :32], input_g_buffer[base : base + N])， 这个size对不上。

**Comment by shiiiivering** [comment]
> 这个代码感觉不太对， tcp.memcpy(input_n_buffer.reshape((N, 32))[:N, :32], input_g_buffer[base : base + N])， 这个size对不上。

这里 dst 和 src 的 shape不都是(0, 32)吗，input_g_buffer是重新声明的形状[data_N, 32]

**Comment by SYangDong** [comment]
这块我看错了，是一样的，应该就是指令不连续取值带来的问题。 如果说类似于，31取的话，效率比较低，能不能取32个，也就是连续的，后面再赋值， 可以对比下性能。

**Comment by zhangyicole** [comment]
@shiiiivering 这里生成的bangc代码，看到的memcpy是连续的，还是有for循环的？
